"""Data-readiness inventory: every file the app expects, its role, and how
users can obtain it. Used by the CLI (`f1-analytics data-status`), the
dashboard readiness banner, and tests.

No file is created here - the app never fabricates data. Missing assets are
reported with an actionable message instead.
"""

from __future__ import annotations

from dataclasses import dataclass
from pathlib import Path

from .. import config
from .loaders import DataNotFoundError, connect_sqlite


@dataclass(frozen=True)
class DataAsset:
    name: str
    path: Path
    role: str
    optional: bool
    ok: bool
    fix: str


def required_assets() -> tuple[DataAsset, ...]:
    """Every data asset the application uses, in evaluation order."""
    return (
        DataAsset(
            "f1.db",
            config.F1_DB_PATH,
            "Canonical historical store (1950-2026, includes lap/telemetry tables). "
            "Required for full analytics, Coach pace, and the race assistant's SQL tool.",
            optional=False,
            ok=config.F1_DB_PATH.exists(),
            fix=(
                "Place a compatible SQLite database at dataset/huggingface/f1.db "
                "(generated by the extraction pipeline described in dataset_overview.txt), "
                "or point F1_DATA_DIR at a directory that contains one. Without it the app "
                "falls back to the tracked Kaggle CSVs (1950-2024) and disables "
                "telemetry-only features (Coach pace, speed traps, circuit pace).",
            ),
        ),
        DataAsset(
            "training_dataset.parquet",
            config.TRAINING_DATASET,
            "Feature table (5094x31) used to train the prediction models.",
            optional=False,
            ok=config.TRAINING_DATASET.exists(),
            fix="Tracked in the repository; regenerate with the dataset tooling if missing.",
        ),
        DataAsset(
            "driver_profiles.parquet",
            config.DRIVER_PROFILES,
            "Driver ratings used by the simulator and analytics enrichment.",
            optional=True,
            ok=config.DRIVER_PROFILES.exists(),
            fix="Tracked in the repository; used for enrichment only. Features degrade gracefully.",
        ),
        DataAsset(
            "tracks.yaml",
            config.TRACKS_YAML,
            "Circuit/simulation parameters used by the simulator and circuit analytics.",
            optional=True,
            ok=config.TRACKS_YAML.exists(),
            fix="Tracked in the repository.",
        ),
        DataAsset(
            "kaggle_csv",
            config.KAGGLE_DIR,
            "14 historical CSV snapshots (1950-2024) used as read-only fallback when f1.db is absent.",
            optional=False,
            ok=config.KAGGLE_DIR.is_dir() and any(config.KAGGLE_DIR.glob("*.csv")),
            fix="Tracked in the repository (dataset/kaggledataset/*.csv).",
        ),
    )


def asset_status() -> dict[str, DataAsset]:
    return {a.name: a for a in required_assets()}


def missing_assets() -> list[DataAsset]:
    return [a for a in required_assets() if not a.ok]


def db_available() -> bool:
    return bool(config.F1_DB_PATH.exists())


def require_db(purpose: str) -> None:
    """Raise DataNotFoundError with an actionable message if f1.db is absent.

    :param purpose: e.g. 'Coach pace analysis' or 'the race assistant SQL tool'.
    """
    if db_available():
        return
    asset = asset_status()["f1.db"]
    raise DataNotFoundError(
        f"{purpose} requires {config.F1_DB_PATH}, which is missing.\n\n{asset.fix}"
    )


def data_status_text() -> str:
    lines = ["Data readiness:"]
    for asset in required_assets():
        state = "ok" if asset.ok else "MISSING"
        lines.append(f"- {state:7s} {asset.name:<28s} {asset.path}")
        if not asset.ok and asset.fix:
            lines.append(f"    fix: {asset.fix}")
    return "\n".join(lines)


def open_f1_db(purpose: str):
    """sqlite3.Connection to f1.db, or a detailed DataNotFoundError."""
    require_db(purpose)
    return connect_sqlite()